spring:
  application:
    name: vehicle-websocket
server:
  port: ${SERVER_PORT:8085}
eureka:
  client:
    enabled: ${EUREKA_ENABLE:false}
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
br:
  com:
    danilopaixao:
      websocket:
        url: ${WEBSOCKET_URL:ws://localhost:8085/livestatus-websocket}
        user: ${WEBSOCKET_USER_ID:spring-restapi-client}
        topic:
           send: /app/updatestatus
           subscribe: /topic/status
      service:
        vehicle:
          url: ${VEHICLE_SERVICE_URL:http://localhost:8083/api/v1}
        driver:
          url: ${DRIVER_SERVICE_URL:http://localhost:8082/api/v1}