spring:
  application:
    name: vehicle-websocket
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
br:
  com:
    danilopaixao:
      websocket:
        url: ${WEBSOCKET_URL:ws://localhost:8085/livestatus-websocket}
      service:
        vehicle:
          protocol: http 
          host: vehicle-service
          version: v1
        driver:
          protocol: http 
          host: driver-service
          version: v1 