spring:
  application:
    name: vehicle-websocket
server:
  port: 8085
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
br:
  com:
    danilopaixao:
      websocket:
        url: ${WEBSOCKET_URL:ws://localhost:8085/livestatus-websocket}
      service:
        vehicle:
          url: http://vehicle-service/api/v1
        driver:
          url: http://driver-service/api/v1